/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint with real DB and AI extractor connectivity checks
         *
         *     Returns:
         *         - status: overall status (healthy/degraded/unhealthy)
         *         - database: DB connection status (connected/disconnected)
         *         - ai_extractor: AI service status (reachable/unreachable/not_configured)
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Health Check
         * @description Health check endpoint with /api prefix for ingress compatibility
         */
        get: operations["api_health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Invoice
         * @description Upload and extract invoice data
         *
         *     Flow:
         *     1. Validate file (type, size)
         *     2. Save to storage with organized path
         *     3. Create invoice record (status='uploaded')
         *     4. Call AI extractor
         *     5. Update invoice with extracted data (status='extracted')
         *     6. Return invoice with AI data
         */
        post: operations["upload_invoice_api_invoices_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Invoice
         * @description Retrieve a single invoice by ID
         *
         *     Args:
         *         invoice_id: Invoice ID to retrieve
         *
         *     Returns:
         *         Invoice data with all fields
         *
         *     Raises:
         *         404: Invoice not found
         */
        get: operations["get_invoice_api_invoices__invoice_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Invoice
         * @description Delete invoice by ID
         *
         *     Args:
         *         invoice_id: Invoice ID to delete
         *
         *     Returns:
         *         204 No Content on success
         *
         *     Raises:
         *         404: Invoice not found
         */
        delete: operations["delete_invoice_api_invoices__invoice_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Invoices
         * @description List invoices with pagination and optional filtering
         *
         *     Args:
         *         skip: Number of records to skip (default: 0)
         *         limit: Maximum number of records to return (default: 20, max: 100)
         *         status: Filter by status (optional): uploaded, extracting, extracted, approved, extraction_failed
         *
         *     Returns:
         *         InvoiceListResponse with invoices array and total count
         */
        get: operations["list_invoices_api_invoices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/{invoice_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Invoice
         * @description Approve invoice with user corrections/validations
         *
         *     Flow:
         *     1. Retrieve invoice from database
         *     2. Validate invoice exists and is in 'extracted' status
         *     3. Save user-validated data (corrections/approvals)
         *     4. Update status to 'approved'
         *     5. Set approved_at timestamp
         *     6. Return updated invoice
         *
         *     Args:
         *         invoice_id: Invoice ID to approve
         *         approval_data: User corrections and validated data
         *
         *     Returns:
         *         Updated invoice with status='approved'
         *
         *     Raises:
         *         404: Invoice not found
         *         400: Invoice not in correct status for approval
         */
        post: operations["approve_invoice_api_invoices__invoice_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_invoice_api_invoices_upload_post */
        Body_upload_invoice_api_invoices_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InvoiceApprove
         * @description Schema for approving invoice with user corrections
         */
        InvoiceApprove: {
            /** Validated Data */
            validated_data: Record<string, never>;
        };
        /**
         * InvoiceListResponse
         * @description Schema for paginated invoice list
         */
        InvoiceListResponse: {
            /** Invoices */
            invoices: components["schemas"]["InvoiceResponse"][];
            /** Total */
            total: number;
        };
        /**
         * InvoiceResponse
         * @description Schema for invoice response
         */
        InvoiceResponse: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Extracted At */
            extracted_at?: string | null;
            /** Approved At */
            approved_at?: string | null;
            /** Status */
            status: string;
            /** Original Filename */
            original_filename: string;
            /** File Type */
            file_type: string;
            /** File Path */
            file_path: string;
            /** File Size */
            file_size?: number | null;
            /** Raw Ai Data */
            raw_ai_data?: Record<string, never> | null;
            /** User Validated Data */
            user_validated_data?: Record<string, never> | null;
            /** Error Message */
            error_message?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    upload_invoice_api_invoices_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_invoice_api_invoices_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_invoice_api_invoices__invoice_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_invoice_api_invoices__invoice_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invoices_api_invoices_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_invoice_api_invoices__invoice_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceApprove"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
